name:                bad-solver
version:             0.1.0.0
github:              "arendsee/bad-solver"
license:             MIT
author:              "Zebulun Arendsee"
maintainer:          "zbwrnz@gmail.com"
copyright:           "2019 Zebulun Arendsee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/arendsee/bad-solver#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bad-solver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bad-solver
